### ISSUE TITLE
No way to run interactive git-adjacent tools "in" gitdot repo

### ISSUE THREAD

**Issue by smammy** [malsyned/gitdot#6]
I sometimes use `lazygit` for examining diffs and staging changes, and I'd like to use it with gitdot. I can do this manually with
```fish
env GIT_DIR=$HOME/.dotfiles.git GIT_WORK_TREE=$HOME lazygit
```
but I'd like to not have to remember what gitdot sets those variables to. Maybe something like
```fish
gitdot run lazygit
```
(Note that I'm (ab)using gitdot to be "opt in" instead of "opt out" by setting `status.showUntrackedFiles = no` in the repository config. Not sure if this changes things.)

**Comment by malsyned** [comment]
I can't think of any reason not to do this. If you have a PR for it, I'd be looking to try to merge it
